version: '3.8'

services:
  my_app:
    build: .
    depends_on:
      - my_db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_IP_URL=my_db
      - DATABASE_PORT_URL=3306

  my_db:
    image: mysql:8.4.4
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fdg_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
